require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseAnalytics', :path => '../../../../capawesome-team/capacitor-firebase/packages/analytics'
  pod 'CapacitorFirebaseApp', :path => '../../../../capawesome-team/capacitor-firebase/packages/app'
  pod 'CapacitorFirebaseAppCheck', :path => '../../../../capawesome-team/capacitor-firebase/packages/app-check'
  pod 'CapacitorFirebaseCrashlytics', :path => '../../../../capawesome-team/capacitor-firebase/packages/crashlytics'
  pod 'CapacitorFirebaseMessaging', :path => '../../../../capawesome-team/capacitor-firebase/packages/messaging'
  pod 'CapacitorFirebasePerformance', :path => '../../../../capawesome-team/capacitor-firebase/packages/performance'
  pod 'CapacitorFirebaseRemoteConfig', :path => '../../../../capawesome-team/capacitor-firebase/packages/remote-config'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../../../capawesome-team/capacitor-firebase/packages/analytics'
end


post_install do |installer|
  assertDeploymentTarget(installer)
end
